[package]
name = "stringparser"
version = "0.1.0"
authors = ["gabecordovado"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libstringparser"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.62"